binop_separator = "Back"
brace_style = "AlwaysNextLine"
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
#match_arm_blocks = false # FIX: see https://github.com/rust-lang/rustfmt/issues/4844
match_block_trailing_comma = true
max_width = 120
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
