# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_adapter_bincode"
version = "0.4.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Bincode filesystem adapter for CLInvoice."

edition = "2018"
license = "GPL3"
readme = "../../README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[dependencies]
# CLInvoice
clinvoice_adapter = {path="../clinvoice_adapter", version="0.4"}
clinvoice_data = {path="../../clinvoice_data", features=["serde_support"], version="0.3"}

# Environment Variable Expansion
shellexpand = "2"

# Serialization
bincode = "1"
